# Setup

[projectInfo]
name = "Install Ruby"
author = "Amit Budhu"
description = "Install Latest Ruby"

[projectSettings]
system = ["Linux","Mac"]
elevatePermission = true

[projectVariables]
rubyVersion = "3.0.0"
gemList = ["bundler","ruboocop"]

[projectSteps]

[projectSteps.installRbenv]
install = "rbenv"

[projectSteps.initRbenv]
run = "rbenv init"

[projectSteps.createPluginsDirectory]
run = "mkdir -p \"$(rbenv root)\"/plugins"

[projectSteps.installRubyBuild]
run = "git clone https://github.com/rbenv/ruby-build.git \"$(rbenv root)\"/plugins/ruby-build"

[projectSteps.runRbenvDoctor]
run = "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash"
validate = "ok"

[projectSteps.installRubyVersion]
run = "rbenv install ${rubyVersion}"

[projectSteps.setRbenvGlobal]
run = "rbenv global ${rubyVersion}"

[projectSteps.reHash]
run = "rbenv hash"

[projectSteps.validateGemHome]
run = "gem env home"
validate = "/gem/home"

[projectSteps.installGems]
run = "gem install ${gemList}"