# Setup

[projectInfo]
name = "Install Ruby"
author = "Amit Budhu"
description = "Install Latest Ruby"

[projectSettings]
# Maybe we can just add
#packageManager = "apt"
system = ["Linux","Mac"]
elevatePermission = true

[projectVariables]
rubyVersion = "3.0.0"
gemList = ["bundler","ruboocop"]

[installRbenv]
install = "rbenv"

[initRbenv]
run = "rbenv init"

[appendBashrc]
append = ["eval \"$(rbenv init -)\"", "/home/amit/.bashrc"]

[sourceBashrc]
run = ". /home/amit/.bashrc"

[createPluginsDirectory]
run = "mkdir -p \"$(rbenv root)\"/plugins"

[installRubyBuild]
run = "git clone https://github.com/rbenv/ruby-build.git \"$(rbenv root)\"/plugins/ruby-build"

[runRbenvDoctor]
run = "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash"
validate = "Auditing installed plugins: OK"

[installRubyVersion]
run = "rbenv install ${rubyVersion}"

[setRbenvGlobal]
run = "rbenv global ${rubyVersion}"

[reHash]
run = "rbenv rehash"

[validateGemHome]
run = "gem env home"
validate = "$(rbenv root)/versions/${rubyVersion}/lib/ruby/gmes/${rubyVersion}"

[installGems]
run = "gem install ${gemList}"