# Setup

[projectInfo]
name = "Install Ruby"
author = "Amit Budhu"
description = "Install Latest Ruby"

#[projectSettings]
#system = ["Linux","Mac"]
#elevatePermission = true

[projectVariables]
rubyVersion = "3.0.0"
gemList = ["bundler","ruboocop"]

[installRbenv]
install = "rbenv"

[initRbenv]
run = "rbenv init"

[createPluginsDirectory]
run = "mkdir -p \"$(rbenv root)\"/plugins"

[installRubyBuild]
run = "git clone https://github.com/rbenv/ruby-build.git \"$(rbenv root)\"/plugins/ruby-build"

[runRbenvDoctor]
run = "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash"
validate = "ok"

[installRubyVersion]
run = "rbenv install ${rubyVersion}"

[setRbenvGlobal]
run = "rbenv global ${rubyVersion}"

[reHash]
run = "rbenv hash"

[validateGemHome]
run = "gem env home"
validate = "/gem/home"

[installGems]
run = "gem install ${gemList}"