# Setup

[projectInfo]
name = "Test Run Command"
author = "Amit Budhu"
description = "Testing Run Command"

[projectSettings]
# Maybe we can just add
#packageManager = "apt"
system = ["Linux","Mac"]
elevatePermission = true

[projectVariables]
rubyVersion = "3.0.0"

[simple]
bash = "gem env home"