# Setup

[projectInfo]
name = "Test Run Command"
author = "Amit Budhu"
description = "Testing Run Command"

[projectSettings]
# Maybe we can just add
#packageManager = "apt"
system = ["Linux","Mac"]
elevatePermission = true

[projectVariables]
simpleSub = "Amit"
sub2 = "Budhu"
installList = ["ruby", "crystal"]
install2 = "crystal"

[listItemsAgain]
run = "ls"

[simple]
run = "echo ${simpleSub} ${sub2}"

[echoNames]
run = "echo ${installList}"

[validateGemHome]
run = "gem env home"
validate = "/gem/home"

#[test]
#run = "sudo apt install ${installList} -y"

#[echoFail]
#run = "echo )"


#[installArrayList]
#install = ["ruby","crystal"]

#[installArraySubList]
#install = "${installList}"

#[installDirectSingle]
#install = "ruby"

#[installSubSingle]
#install = "${install2}"