# Setup

[projectInfo]
name = "Test Run Command"
author = "Amit Budhu"
description = "Testing Run Command"

[projectSettings]
# Maybe we can just add
#packageManager = "apt"
system = ["Linux","Mac"]
elevatePermission = true

[projectVariables]
simpleSub = "Amit"
sub2 = "Budhu"
installList = ["ruby", "crystal"]
install2 = "crystal"

[simple]
run = "curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash"